---
AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation template to create load testing resources
Parameters:
  URL:
    Type: String
    Description: The URL to load test
  DesiredTaskCount:
    Type: Number
    Description: Number of tasks to run for the load test
    Default: 5
    MinValue: 1
    MaxValue: 20
  Tries:
    Type: Number
    Description: Number of tries per load test
    Default: 1000
  Sleep:
    Type: Number
    Description: Time in seconds to sleep between tries
    Default: 0.1
  MasterRegion:
    Type: string
    Description: When using Stacksets, the region to deliver all the logs to
    Default:
      Ref: "AWS::Region"
Resources:
  LoadTesterLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/color-info-taskdef
      RetentionInDays: 365
  LoadTesterTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - LoadTesterLogGroup
    Properties:
      RequiresCompatibilities:
        - FARGATE
      Volumes: []
      NetworkMode: awsvpc
      Memory: 2048
      Cpu: 512
      ExecutionRoleArn:
        Fn::Join:
          - ""
          - - "arn:aws:iam::"
            - Ref: "AWS::AccountId"
            - ":role/ecsTaskExecutionRole"
      PlacementConstraints: []
      Family: simple-load-tester-taskdef
      ContainerDefinitions:
        - Name: load-test
          Image: yashdalfthegray/simple-load-tester:latest
          Essential: true
          Command:
            - "--url"
            - Ref: URL
            - "--times"
            - Ref: Tries
            - "--sleep"
            - Ref: Sleep
          LogConfiguration:
            LogDriver: awslogs
            Options:
              "awslogs-group": "/ecs/simple-load-tester-taskdef"
              "awslogs-region":
                Ref: MasterRegion
              "awslogs-stream-prefix": "ecs"
  LoadTesterCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: "load-test-cluster"
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
  PublicSubnetAz1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: Vpc
      CidrBlock: 10.0.0.0/24
      AvailabilityZone:
        Fn::Select:
          - "0"
          - Fn::GetAZs:
              Ref: AWS::Region
  PublicSubnetAz2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: Vpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone:
        Fn::Select:
          - "1"
          - Fn::GetAZs:
              Ref: AWS::Region
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: Vpc
      InternetGatewayId:
        Ref: InternetGateway
  RouteViaIgw:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: Vpc
  PublicRouteViaIgw:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId:
        Ref: RouteViaIgw
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnetAz1
      RouteTableId:
        Ref: RouteViaIgw
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnetAz2
      RouteTableId:
        Ref: RouteViaIgw
  LoadTestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the load test tasks
      VpcId:
        Ref: Vpc
  LoadTesterService:
    Type: AWS::ECS::Service
    DependsOn:
      - LoadTesterCluster
      - LoadTesterTaskDefinition
    Properties:
      Cluster:
        Ref: LoadTesterCluster
      DesiredCount:
        Ref: DesiredTaskCount
      LaunchType: FARGATE
      ServiceName: load-test-service
      TaskDefinition:
        Ref: LoadTesterTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Ref: LoadTestSecurityGroup
          Subnets:
            - Ref: PublicSubnetAz1
            - Ref: PublicSubnetAz2
